// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Details: typeof import('./src/components/UserPage/Details.vue')['default']
    History: typeof import('./src/components/UserPage/History.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MShopPage: typeof import('./src/components/Shop/MShopPage.vue')['default']
    OverView: typeof import('./src/components/UserPage/OverView.vue')['default']
    PayWay: typeof import('./src/components/UserPage/PayWay.vue')['default']
    Product: typeof import('./src/components/product.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Security: typeof import('./src/components/UserPage/Security.vue')['default']
    ShopCart: typeof import('./src/components/UserPage/ShopCart.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    UserPage: typeof import('./src/components/UserPage.vue')['default']
  }
}
